import React from 'react'
import Head from 'next/head'
import { ArrowBackIcon } from '@chakra-ui/icons'
import images from '../public/dataImage.json'
import Link from 'next/link';
import { Box, Flex, Card, Image, CardBody, Heading, Text, Stack, useColorModeValue } from '@chakra-ui/react';


const StarshipDetail = ({ starship }) => {
  const image = images.find((image) => image.name === starship.name);
  //console.log(starship);
  const bg = "linear-gradient(127.09deg, rgba(6, 11, 40, 0.94) 19.41%, rgba(10, 14, 35, 0.49) 76.65%)"

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet" />
      </Head>
      <Flex>
        <Link href="/">
          <ArrowBackIcon boxSize={8} mb="3" color='yellow.400' />
        </Link>
      </Flex>
      <Box>
        <Card
          direction={{ base: 'column', sm: 'row' }}
          overflow='hidden'
          variant='outline'
          boxShadow="10px 10px 47px 0px rgba(29, 209, 161,0.2)"
          bg={bg}
          p={30}
        >
          <Image
            objectFit='cover'
            maxW={{ base: '100%', sm: '200px', md: '400px' }}
            src={image.img}
            alt={starship.name}
          />
          <Stack textAlign="justify">
            <CardBody>
              <Heading color="orange.400" size='md'>{starship.name}</Heading>
              <Text py='2'>
               <Text color="orange.200" as="span">Model:</Text> {starship.model}
              </Text>
              <Text py='2'>
                <Text color="orange.200" as="span">Max Speed: </Text>{starship.max_atmosphering_speed}
              </Text>
              <Text py='2'>
               <Text as="span" color="orange.200" >Manufacturer: </Text> {starship.manufacturer}
              </Text>
              <Text py='2'>
               <Text as="span" color="orange.200">Cargo Capacity: </Text>{starship.cargo_capacity}
              </Text>
              <Text py='2'>
               <Text as="span" color="orange.200">Passengers: </Text>{starship.passengers}
              </Text>
              <Text py='2'>
               <Text as="span" color="orange.200">Crew: </Text>{starship.crew}
              </Text>
            </CardBody>
          </Stack>
        </Card>
      </Box>
    </>
  )
}

export default StarshipDetail