import { Box, Button, Card, Image, Center, CardFooter, Stack, Heading, Flex } from '@chakra-ui/react'
import { ArrowBackIcon } from '@chakra-ui/icons'
import images from '../public/dataImage.json'
import { useStarshipsContext } from '@/context/StarshipsContext'
import Link from 'next/link'
import Head from 'next/head'

const Favorites = () => {

    const { favorite, removeFavorite } = useStarshipsContext();

    //console.log(favorite);
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
                <link rel="preconnect" href="https://fonts.googleapis.com" />
                <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
                <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet" />
            </Head>
            <Flex><Link href="/"> <ArrowBackIcon boxSize={8} mb="3" color='yellow.400' /></Link></Flex>
            <Flex gap='20' justifyContent='center' flexWrap="wrap" mb="6" mt="5">
                {
                    favorite && favorite.length > 0 ? favorite.map((starship) => {
                        const image = images.find((image) => image.name === starship.name)
                        return (
                            <Box key={starship.name}>
                                <Card bg='transparent' borderRadius="5"
                                    _hover={{
                                        boxShadow: "10px 10px 47px 0px rgba(29, 209, 161,0.2)",
                                        transition: "400ms"
                                    }}
                                    width="300px"
                                >
                                    <Link href={`/${starship.name}`}>
                                        <Image
                                            src={image.img}
                                            style={{
                                                width: "300px",
                                                height: "300px",
                                                borderRadius: "5px",
                                            }}
                                        />
                                    </Link>
                                    <Stack>
                                        <Heading size="md" pt='4' color='#ffc404' >
                                            {starship.name}
                                        </Heading>
                                    </Stack>
                                    <Center>
                                        <CardFooter>
                                            <Button

                                                color='#ffc404' onClick={() => removeFavorite(starship)}>Remove Favorite</Button>
                                        </CardFooter>
                                    </Center>
                                </Card>
                            </Box>)
                    }) : <Box>You haven't added any movies to your favorites yet !</Box>
                }</Flex>
        </>
    )
}

export default Favorites