import Head from 'next/head'
import { Box } from '@chakra-ui/react'
import Search from '@/components/Search'
import CardList from '@/components/CardList'


export default function Home() {

  return (
    <>
      <Head>
        <title>Star Wars / Starships</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Bruno+Ace+SC&display=swap" rel="stylesheet" />
      </Head>
      <Box justifyContent="center" alignItems="center" flexDirection="column">
        <Search />
        <CardList />
      </Box>
    </>
  )
}
