import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { Box, Flex,Input } from '@chakra-ui/react'


import Search from '@/components/Search'
import CardList from '@/components/CardList'



const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>
      <Head >
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    
      <Box  justifyContent="center" alignItems="center" flexDirection="column">
         <Search/>
         <CardList/>
      </Box>
    </>
  )
}
